name: Update playlist

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Update playlist
        run: |
          git config user.name "PlaylistBot" || true
          git config user.email "playlistbot@users.noreply.github.com" || true
          python3 ./make_playlist.py
          git add playlist.m3u8 playlists
          git diff --staged --quiet && exit 0
          git commit --quiet -m "Update Playlist (GitHub Actions)"
          git push origin HEAD:master
